<?php

// This file was generated by running "composer dump-env dev"

return array (
  'APP_ENV' => 'dev',
  //'APP_SECRET' => '3c586556ec9ad45f15d9cc7519e6a8c7',
  //'CORS_ALLOW_ORIGIN' => '*',
  'DATABASE_URL' => 'mysql://b923c2350e2e98:53598933@eu-cdbr-west-03.cleardb.net/heroku_bef80f3743ee9c8?reconnect=true',
  
);